BE/.gitignore, BE/build.gradle, BE/src/main/java/com/codesquad/issuetracker/config/WebConfig.java, BE/src/main/java/com/codesquad/issuetracker/user/component/GitHubOauthIosValues.java, BE/src/main/java/com/codesquad/issuetracker/user/component/GitHubOauthValues.java, BE/src/main/java/com/codesquad/issuetracker/user/component/GitHubOauthWebValues.java, BE/src/main/java/com/codesquad/issuetracker/user/component/JwtUtils.java, BE/src/main/java/com/codesquad/issuetracker/user/controller/AuthController.java, BE/src/main/java/com/codesquad/issuetracker/user/dto/AccessTokenRequest.java, BE/src/main/java/com/codesquad/issuetracker/user/dto/AccessTokenResponse.java, BE/src/main/java/com/codesquad/issuetracker/user/dto/GithubUser.java, BE/src/main/java/com/codesquad/issuetracker/user/dto/JwtResponse.java, BE/src/main/java/com/codesquad/issuetracker/user/service/GithubLoginService.java, BE/src/main/java/com/codesquad/issuetracker/user/service/JwtUtils.java, BE/src/main/resources/application.properties
- web github 로그인 구현
- ios github 로그인 구현
=> [Be] github login 기능 구현

frontend/src/components/pages/LoginPage.jsx, frontend/src/styles/StyledButtons.jsx
=> [FE] chore: 로그인 버튼 Material-UI 적용

BE/build.gradle, BE/src/main/java/com/codesquad/issuetracker/milestone/controller/MilestoneController.java, BE/src/main/java/com/codesquad/issuetracker/milestone/domain/Milestone.java, BE/src/main/java/com/codesquad/issuetracker/milestone/dto/MilestoneRequestDto.java, BE/src/main/java/com/codesquad/issuetracker/milestone/dto/MilestoneResponseDto.java, BE/src/main/java/com/codesquad/issuetracker/milestone/dto/MilestoneWrapper.java, BE/src/main/java/com/codesquad/issuetracker/milestone/dto/MilestonesWrapper.java, BE/src/main/java/com/codesquad/issuetracker/milestone/infra/MilestoneRepository.java, BE/src/main/java/com/codesquad/issuetracker/milestone/service/MilestoneService.java, BE/src/main/resources/application.properties, BE/src/test/java/com/codesquad/issuetracker/milestone/domain/MilestoneTest.java
- 전체 마일스톤 조회
- 마일스톤 등록
- 마일스톤 변경
- 마일스톤 삭제
=> [BE] Milestone CRUD

BE/src/main/java/com/codesquad/issuetracker/comment/controller/CommentController.java, BE/src/main/java/com/codesquad/issuetracker/comment/domain/Comment.java, BE/src/main/java/com/codesquad/issuetracker/comment/dto/CommentRequest.java, BE/src/main/java/com/codesquad/issuetracker/comment/dto/CommentResponse.java, BE/src/main/java/com/codesquad/issuetracker/comment/dto/CommentWrapper.java, BE/src/main/java/com/codesquad/issuetracker/comment/dto/CommentsWrapper.java, BE/src/main/java/com/codesquad/issuetracker/comment/infra/CommentRepository.java, BE/src/main/java/com/codesquad/issuetracker/comment/service/CommentService.java
- comment 추가 기능 완료.
- comment 수정 기능 완료.
=> [BE] comment 기능 구현

frontend/src/MyRecoil/atom.js, frontend/src/MyRecoil/index.js, frontend/src/components/Issues/IssueList/IssuesHeader.jsx, frontend/src/components/Issues/Menu/MenuFilterBar.jsx, frontend/src/components/common/ButtonGroup.jsx, frontend/src/components/common/DropDownButton.jsx, frontend/src/components/common/FilterModal.jsx, frontend/src/components/pages/MainPage.jsx, frontend/src/data.js, frontend/src/images/radio_button_checked.svg, frontend/src/images/radio_button_default.svg, frontend/src/styles/StyledButtons.jsx, frontend/src/styles/theme.js
- dev로 Merge를 위한 PR입니다~ 내일 오프에서 충돌 해결 및 코드 리뷰 후 merge 해보아요~!
- recoil selector 사용이 필요해서 잠시 기존 recoil을 적용해야할 것 같습니다..흑흑 ㅜ
=> [FE] FilterModal 기능 구현

frontend/src/RecoilStore/Atoms.jsx, frontend/src/components/Issues/IssueList/IssueCard.jsx, frontend/src/components/Issues/IssueList/IssuesHeader.jsx, frontend/src/index.jsx
=> [FE] : fix: 체크박스 로직 수정

frontend/src/RecoilStore/Atoms.jsx, frontend/src/components/Issues/IssueList/IssuesHeader.jsx, frontend/src/components/NewIssues/NewIssueForm.jsx, frontend/src/components/NewIssues/NewIssueInput.jsx, frontend/src/components/common/CancelButton.jsx, frontend/src/components/common/CommentInput.jsx, frontend/src/components/common/FilterModal.jsx, frontend/src/components/common/Header.jsx, frontend/src/components/common/IssueCategoryList.jsx, frontend/src/components/common/SubmitButton.jsx, frontend/src/components/pages/NewIssuePage.jsx, frontend/src/data.js, frontend/src/styles/StyledButtons.jsx, frontend/src/styles/theme.js, frontend/src/util/getEngKey.js, frontend/src/util/getUserInfo.js
=> [FE] new issue 페이지 HTML 틀 잡기

frontend/src/components/Issues/IssueList/IssueCard.jsx, frontend/src/components/Issues/IssueList/IssuesHeader.jsx, frontend/src/components/Issues/Menu/MenuTab.jsx, frontend/src/components/Labels/LabelCard.jsx, frontend/src/components/Labels/Labels.jsx, frontend/src/components/Labels/LabelsHeader.jsx, frontend/src/components/Milestones/MilestoneCard.jsx, frontend/src/components/Milestones/Milestones.jsx, frontend/src/components/Milestones/MilestonesHeader.jsx, frontend/src/components/common/ButtonGroup.jsx, frontend/src/components/common/Navigator.jsx, frontend/src/components/pages/LabelsPage.jsx, frontend/src/components/pages/MainPage.jsx, frontend/src/components/pages/MilestonesPage.jsx, frontend/src/styles/StyledCards.jsx, frontend/src/util/getGridRateStyle.js
=> [FE] 레이블 페이지와 마일스톤 페이지 HTML 구조화 적용

BE/src/main/java/com/codesquad/issuetracker/auth/component/JwtUtils.java, BE/src/main/java/com/codesquad/issuetracker/auth/interceptor/AuthInterceptor.java, BE/src/main/java/com/codesquad/issuetracker/comment/controller/CommentController.java, BE/src/main/java/com/codesquad/issuetracker/comment/domain/Comment.java, BE/src/main/java/com/codesquad/issuetracker/comment/dto/CommentRequest.java, BE/src/main/java/com/codesquad/issuetracker/comment/infra/CommentRepository.java, BE/src/main/java/com/codesquad/issuetracker/comment/service/CommentService.java, BE/src/main/java/com/codesquad/issuetracker/config/WebConfig.java, BE/src/main/java/com/codesquad/issuetracker/issue/controller/IssueController.java, BE/src/main/java/com/codesquad/issuetracker/issue/domain/Issue.java, BE/src/main/java/com/codesquad/issuetracker/issue/dto/AssigneeIdRequest.java, BE/src/main/java/com/codesquad/issuetracker/issue/dto/IssueCreateRequest.java, BE/src/main/java/com/codesquad/issuetracker/issue/dto/IssueRequest.java, BE/src/main/java/com/codesquad/issuetracker/issue/dto/IssueResponse.java, BE/src/main/java/com/codesquad/issuetracker/issue/dto/IssueSummaryResponse.java, BE/src/main/java/com/codesquad/issuetracker/issue/dto/IssueWrapper.java, BE/src/main/java/com/codesquad/issuetracker/issue/dto/IssuesWrapper.java, BE/src/main/java/com/codesquad/issuetracker/issue/dto/LabelIdRequest.java, BE/src/main/java/com/codesquad/issuetracker/issue/dto/MilestoneIdRequest.java, BE/src/main/java/com/codesquad/issuetracker/issue/infra/IssueRepository.java, BE/src/main/java/com/codesquad/issuetracker/issue/repository/IssueRepository.java, BE/src/main/java/com/codesquad/issuetracker/issue/service/IssueService.java, BE/src/main/java/com/codesquad/issuetracker/milestone/domain/Milestone.java, BE/src/main/java/com/codesquad/issuetracker/milestone/dto/MilestoneResponseDto.java, BE/src/main/java/com/codesquad/issuetracker/user/domain/User.java, BE/src/main/java/com/codesquad/issuetracker/user/dto/UserDto.java, BE/src/test/java/com/codesquad/issuetracker/issue/infra/IssueRepositoryTest.java, BE/src/test/java/com/codesquad/issuetracker/issue/repository/IssueRepositoryTest.java
- 이슈 조회
- 이슈를 생성한다.
- 이슈를 수정한다.
- 이슈에 라벨을 추가한다.
- 이슈에 라벨을 삭제한다.
- 이슈에 담당자를 추가한다.
- 이슈에 담당자를 삭제한다.
- 이슈에 마일 스톤을 추가한다.
- 이슈에 마일 스톤을 제거한다.
=> [BE] issue 기본 기능 구현

BE/build.gradle, BE/src/main/java/com/codesquad/issuetracker/issue/domain/Issue.java, BE/src/main/resources/application.properties
=> [BE] MySQL DB

frontend/src/components/Milestones/MilestoneCard.jsx, frontend/src/components/Milestones/MilestoneInput.jsx, frontend/src/components/Milestones/Milestones.jsx, frontend/src/components/Milestones/MilestonesHeader.jsx, frontend/src/components/common/CloseButton.jsx, frontend/src/components/pages/MilestonesPage.jsx, frontend/src/hooks/useFetchGet.jsx, frontend/src/util/getPercent.js
=> [FE] Fe/feat/milestone

frontend/src/components/pages/MilestonesPage.jsx, frontend/src/hooks/useFetchGet.jsx
=> [FE] feat: useFecth 커스텀 훅

BE/src/main/java/com/codesquad/issuetracker/auth/component/JwtUtils.java, BE/src/main/java/com/codesquad/issuetracker/auth/interceptor/AuthInterceptor.java, BE/src/main/java/com/codesquad/issuetracker/auth/service/GithubLoginService.java, BE/src/main/java/com/codesquad/issuetracker/comment/controller/CommentController.java, BE/src/main/java/com/codesquad/issuetracker/comment/service/CommentService.java, BE/src/main/java/com/codesquad/issuetracker/issue/controller/IssueController.java, BE/src/main/java/com/codesquad/issuetracker/issue/domain/Issue.java, BE/src/main/java/com/codesquad/issuetracker/user/domain/User.java, BE/src/main/java/com/codesquad/issuetracker/user/dto/UserDto.java, BE/src/test/java/com/codesquad/issuetracker/milestone/domain/MilestoneTest.java
=> [BE] review 반영

frontend/src/RecoilStore/Atoms.jsx, frontend/src/components/Milestones/MilestoneInput.jsx, frontend/src/components/Milestones/Milestones.jsx, frontend/src/components/common/Button/ButtonGroup.jsx, frontend/src/components/common/Navigator.jsx
* 마일스톤 get, post, put 완성
* 마일스톤 개수 버튼그룹에 렌더링
=> [FE] Fe/feat/milestone dev

frontend/src/RecoilStore/Atoms.jsx, frontend/src/components/Labels/LabelCard.jsx, frontend/src/components/Labels/LabelInput.jsx, frontend/src/components/Labels/Labels.jsx, frontend/src/components/common/Navigator.jsx, frontend/src/data.js, frontend/src/util/fetchData.js
- GET 완료 
- POST 오류 미해결 
- 나머지 버튼 로직 구현 완료 api 연동 필요
=> [FE] label page API 연동

BE/build.gradle, BE/src/main/java/com/codesquad/issuetracker/config/AmazonS3Config.java, BE/src/main/java/com/codesquad/issuetracker/image/component/S3Uploader.java, BE/src/main/java/com/codesquad/issuetracker/image/controller/ImageUploadController.java, BE/src/main/java/com/codesquad/issuetracker/image/dto/Image.java, BE/src/main/java/com/codesquad/issuetracker/image/dto/ImageWrapper.java, BE/src/main/java/com/codesquad/issuetracker/image/service/ImageUploadService.java, BE/src/main/resources/application-aws.properties, BE/src/main/resources/application.properties
- 이미지 업로드 요청시, s3 bucket에 해당 이미지 저장
- 이미지 url로 응답
=> [BE] 이미지 업로드 기능

BE/src/main/java/com/codesquad/issuetracker/auth/component/JwtUtils.java, BE/src/main/java/com/codesquad/issuetracker/auth/interceptor/AuthInterceptor.java, BE/src/main/java/com/codesquad/issuetracker/auth/service/GithubLoginService.java, BE/src/main/java/com/codesquad/issuetracker/comment/service/CommentService.java, BE/src/main/java/com/codesquad/issuetracker/exception/BadRequestException.java, BE/src/main/java/com/codesquad/issuetracker/exception/BadTokenRequestException.java, BE/src/main/java/com/codesquad/issuetracker/exception/CommentNotFoundException.java, BE/src/main/java/com/codesquad/issuetracker/exception/HttpException.java, BE/src/main/java/com/codesquad/issuetracker/exception/HttpExceptionHandler.java, BE/src/main/java/com/codesquad/issuetracker/exception/IssueNotFoundException.java, BE/src/main/java/com/codesquad/issuetracker/exception/LabelNotFoundException.java, BE/src/main/java/com/codesquad/issuetracker/exception/MilestoneNotFoundException.java, BE/src/main/java/com/codesquad/issuetracker/exception/NotFoundException.java, BE/src/main/java/com/codesquad/issuetracker/exception/S3UploadFailException.java, BE/src/main/java/com/codesquad/issuetracker/exception/UnauthorizedException.java, BE/src/main/java/com/codesquad/issuetracker/exception/UserNotFoundException.java, BE/src/main/java/com/codesquad/issuetracker/exception/dto/HttpExceptionResponse.java, BE/src/main/java/com/codesquad/issuetracker/image/component/S3Uploader.java, BE/src/main/java/com/codesquad/issuetracker/issue/service/IssueService.java, BE/src/main/java/com/codesquad/issuetracker/label/service/LabelService.java, BE/src/main/java/com/codesquad/issuetracker/milestone/service/MilestoneService.java
=> [BE] 예외처리 기능 구현

frontend/src/components/IssueDetail/IssueDatailHeader.jsx, frontend/src/components/IssueDetail/IssueDetailCommentCard.jsx, frontend/src/components/IssueDetail/IssueDetailComments.jsx, frontend/src/components/Labels/LabelCard.jsx, frontend/src/components/Labels/LabelInput.jsx, frontend/src/components/NewIssues/NewIssueForm.jsx, frontend/src/components/common/CommentInput.jsx, frontend/src/components/pages/IssueDetailPage.jsx, frontend/src/components/pages/NewIssuePage.jsx, frontend/src/images/alert-circle.svg, frontend/src/styles/OpenLabel.jsx, frontend/src/styles/StyledLayout.jsx
* 이슈 디테일 페이지 대략적인 스타일링 완료
* common 컴포넌트인 카테고리 리스트 추가 필요
=> [FE] Fe/feat/issue detail 스타일링 

frontend/package-lock.json, frontend/package.json, frontend/src/components/IssueDetail/IssueDetailCommentCard.jsx, frontend/src/components/common/CommentInput.jsx, frontend/src/components/common/MarkdownRenderer.jsx, frontend/src/util/API.js, frontend/src/util/fetchImage.js, frontend/yarn.lock
이미지 업로드 한 뒤 옆의 submit 버튼을 누르면 마크다운 문서에 이미지가 추가됩니다.
=> [FE] feat: 코멘트 이미지 업로드 기능 추가

frontend/src/RecoilStore/Atoms.jsx, frontend/src/components/NewIssues/NewIssueForm.jsx, frontend/src/components/common/IssueCategory/Assignee.jsx, frontend/src/components/common/IssueCategory/IssueCategory.jsx, frontend/src/components/common/IssueCategory/IssueCategoryList.jsx, frontend/src/components/common/IssueCategory/IssueCategoryModal.jsx, frontend/src/components/common/IssueCategory/Label.jsx, frontend/src/components/common/IssueCategory/MileStone.jsx, frontend/src/data.js, frontend/src/util/getCategoryText.js
=> [FE] new issue 구현

frontend/src/RecoilStore/Atoms.jsx, frontend/src/components/NewIssues/NewIssueForm.jsx, frontend/src/components/common/CommentInput.jsx
코멘트 인풋 및 이슈 인풋 상태관리를 통해 이슈 POST 사전작업중..
=> [FE] feat: 코멘트 인풋 및 이슈 인풋 상태관리

frontend/src/components/Issues/IssueList/IssueCard.jsx, frontend/src/components/Issues/IssueList/IssuesHeader.jsx, frontend/src/components/NewIssues/NewIssueForm.jsx, frontend/src/components/common/LabelBadge.jsx
* 이슈 페이지 라벨 레이아웃 위치 조정
* 새 이슈 페이지에서 완료 버튼 누르면 메인 화면으로 이동
=> [FE] feat: 이슈 페이지 스타일 수정

frontend/src/RecoilStore/Atoms.jsx, frontend/src/components/IssueDetail/IssueDetailCommentCard.jsx, frontend/src/components/IssueDetail/IssueDetailComments.jsx, frontend/src/components/IssueDetail/IssueDetailHeader.jsx, frontend/src/components/Labels/Labels.jsx, frontend/src/components/Milestones/MilestoneInput.jsx, frontend/src/components/Milestones/Milestones.jsx, frontend/src/components/Milestones/MilestonesHeader.jsx, frontend/src/components/common/CommentInput.jsx, frontend/src/components/common/MarkdownRenderer.jsx, frontend/src/components/common/Navigator.jsx, frontend/src/components/pages/IssueDetailPage.jsx, frontend/src/util/API.js
이슈 디테일 페이지 내에서 fetch된 이슈 정보를 렌더링했습니다.
타임스탬프는 백엔드분들이 서버 시간을 영국시간으로 설정해놓으셔서 약간 이상하게 나오구요.
이슈 디테일 페이지 내에서 담당자, 라벨, 마일스톤,  설정하는 기능은 아직 추가안했습니다~~
=> [FE] 이슈상세페이지 데이터 fetch 후 렌더링

frontend/src/RecoilStore/Atoms.jsx, frontend/src/components/IssueDetail/IssueDetailHeader.jsx, frontend/src/components/Issues/IssueList/IssueCard.jsx, frontend/src/components/Issues/IssueList/IssuesHeader.jsx, frontend/src/components/Issues/Menu/MenuFilterBar.jsx, frontend/src/components/common/CommentInput.jsx, frontend/src/components/common/FilterModal.jsx, frontend/src/components/pages/IssueDetailPage.jsx, frontend/src/data.js, frontend/src/util/getEngKey.js
* 이슈 상세 페이지에서 이슈 제목 편집
* 이슈 상세 페이지에서 이슈 열기/닫기
* 선택한 이슈들 한번에 열기/닫기
* 코멘트 수정
=> [FE] 이슈 관련 기능 추가

frontend/src/RecoilStore/Atoms.jsx, frontend/src/components/IssueDetail/IssueDetailCommentCard.jsx, frontend/src/components/Issues/IssueList/IssueCard.jsx, frontend/src/components/Issues/IssueList/IssueList.jsx, frontend/src/components/Issues/IssueList/IssuesHeader.jsx, frontend/src/components/common/CommentInput.jsx, frontend/src/components/common/FilterModal.jsx
=> [FE] 선택된 이슈들 열기/닫기 + 이슈 코멘트 수정 기능 추가

frontend/src/RecoilStore/Atoms.jsx, frontend/src/components/common/IssueCategory/IssueCategoryModal.jsx, frontend/src/components/pages/IssueDetailPage.jsx, frontend/src/util/API.js
구현 목록 
- 마일스톤 선택 버그 해결 
- 담당자, 라벨, 마일스톤 수정 구현 완료
준제로.. 드디어 고지가 보이네요 후후..
확인 후 Merge 부탁 드려요~!
=> Fe/feat/issue detail 구현 완료

frontend/src/components/IssueDetail/IssueDetailCommentCard.jsx, frontend/src/components/common/CommentInput.jsx
* 코멘트 수정 버튼을 눌렀을 때 기존 코멘트 내용이 다 사라지는 버그가 있었는데요. 없앴습니다.
* 코멘트 수정 과정에서 갑자기 마음이 변할 때를 위해 코멘트 수정 취소 버튼을 추가했습니다.
=> [FE] fix: 코멘트 수정시 기존 내용 렌더링, 코멘트 편집 취소 기능 추가

frontend/src/components/common/IssueCategory/IssueCategoryModal.jsx, frontend/src/components/common/IssueCategory/Milestone.jsx
- 프로그레스바 버그 해결 
- 필터 모달 스타일 수정
=> [FE] 버그 해결, 스타일 수정 

frontend/src/components/Issues/IssueList/IssueList.jsx, frontend/src/components/Issues/Menu/MenuFilterBar.jsx, frontend/src/components/common/FilterModal.jsx, frontend/src/data.js
=> [FE] 필터모달 목데이터에서 fetched 데이터로 변경

frontend/src/components/Issues/Menu/Menu.jsx, frontend/src/components/common/CommentInput.jsx, frontend/src/components/pages/MainPage.jsx
이 버그는 고쳤는데.. 새 코멘트 추가하면 작성한 내용이 안사라지는 버그가 또 등장 ㅋ 개굴
=> [FE] 코멘트 편집 누르면 새 코멘트 부분도 채워지는 버그 수정

frontend/src/components/Milestones/Milestones.jsx, frontend/src/components/Milestones/MilestonesHeader.jsx, frontend/src/components/common/Button/DropDownButton.jsx, frontend/src/components/common/FilterModal.jsx, frontend/src/data.js, frontend/src/util/getFilterList.js
* 로컬스토리지에 토큰 정보가 없으면 로그인 페이지에 접근이 안되는 버그 (필터 아이템 목록을 상태로 관리해서 해결)
* 열린/닫힌 마일스톤 개수 버튼을 마일스톤 개수만 보여주는 것으로 변경
=> [FE] 자잘한 버그 수정
